### ISSUE TITLE
Cylinder problem not running

### ISSUE THREAD

**Issue by jorgensd** [KVSlab/OasisMove#27]
MWE:
```bash
(base) dokken@dokken-XPS-9320:~/Documents/src/OasisMove$ git checkout main
M	tests/test_NSfracStep.py
Already on 'main'
Your branch is up to date with 'origin/main'.
(base) dokken@dokken-XPS-9320:~/Documents/src/OasisMove$ git pull
Already up to date.
(base) dokken@dokken-XPS-9320:~/Documents/src/OasisMove$ docker run -ti --network=host -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v $(pwd):/root/shared -w /root/shared --rm  ghcr.io/scientificcomputing/fenics:2023-04-21 
root@dokken-XPS-9320:~/shared# python3 -m pip install -e .
Obtaining file:///root/shared
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: oasismove
  Building editable for oasismove (pyproject.toml) ... done
  Created wheel for oasismove: filename=oasismove-0.4.0-0.editable-py3-none-any.whl size=28075 sha256=915eaeb82b2106bb3e5fc59c9b3ba23e11ccc166ac486ed7b5f56917075dc75d
  Stored in directory: /tmp/pip-ephem-wheel-cache-lgo2mk2d/wheels/c5/3c/42/8c2c0a897305369ee7da3defe8b4df101590516f4246c903e8
Successfully built oasismove
Installing collected packages: oasismove
Successfully installed oasismove-0.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
root@dokken-XPS-9320:~/shared# cd tests/
root@dokken-XPS-9320:~/shared/tests# oasismove NSfracStep problem=Cylinder solver=IPCS_ABCN
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
Start                              101 MB        101 MB        302 MB        302 MB
Importing problem module Cylinder:
/root/shared/src/oasismove/problems/NSfracStep/Cylinder.py
Authorization required, but no authorization protocol specified
Authorization required, but no authorization protocol specified
=== Starting simulation for Cylinder problem ===
Running with the following parameters:
{'AB_projection_pressure': False,
 'DynamicSmagorinsky': {'Cs_comp_step': 1},
 'KineticEnergySGS': {'Ce': 1.05, 'Ck': 0.08},
 'ModifiedCross': {'a_param': 0.34,
                   'lam': 3.736,
                   'm_param': 2.406,
                   'mu_inf': 0.00372,
                   'mu_o': 0.09,
                   'rho': 1085},
 'Smagorinsky': {'Cs': 0.1677},
 'T': 100,
 'Wale': {'Cw': 0.325},
 'backflow_beta': 0.2,
 'backflow_facets': [],
 'checkpoint': 50,
 'compute_velocity_and_pressure': True,
 'dt': 0.01,
 'dynamic_mesh': False,
 'folder': 'results',
 'iters_on_first_timestep': 2,
 'killtime': None,
 'krylov_solvers': {'absolute_tolerance': 1e-08,
                    'error_on_nonconvergence': False,
                    'maximum_iterations': 200,
                    'monitor_convergence': True,
                    'nonzero_initial_guess': True,
                    'relative_tolerance': 1e-08,
                    'report': False},
 'krylov_solvers_w': {'absolute_tolerance': 0.001,
                      'monitor_convergence': False,
                      'relative_tolerance': 0.001,
                      'report': False},
 'les_model': 'NoModel',
 'max_error': 1e-06,
 'max_iter': 2,
 'mesh_velocity_krylov_solver': {'preconditioner_type': 'amg',
                                 'solver_type': 'gmres'},
 'nn_model': 'NoModel',
 'nu': 0.01,
 'nu_nn_krylov_solver': {'method': 'default',
                         'preconditioner_type': 'jacobi',
                         'solver_type': 'cg'},
 'nut_krylov_solver': {'method': 'WeightedAverage',
                       'preconditioner_type': 'jacobi',
                       'solver_type': 'cg'},
 'output_timeseries_as_vector': True,
 'plot_interval': 10,
 'pressure_degree': 1,
 'pressure_krylov_solver': {'preconditioner_type': 'hypre_amg',
                            'solver_type': 'gmres'},
 'print_intermediate_info': 100,
 'print_velocity_pressure_convergence': False,
 'restart_folder': None,
 'save_step': 50,
 'scalar_krylov_solver': {'preconditioner_type': 'jacobi',
                          'solver_type': 'bicgstab'},
 'solver': 'IPCS_ABCN_Move',
 't': 0.0,
 'testing': False,
 'tstep': 0,
 'use_krylov_solvers': True,
 'use_supg': False,
 'velocity_degree': 2,
 'velocity_krylov_solver': {'preconditioner_type': 'jacobi',
                            'solver_type': 'bicgstab'},
 'velocity_update_solver': {'low_memory_version': False,
                            'method': 'default',
                            'preconditioner_type': 'jacobi',
                            'solver_type': 'cg'}}
Traceback (most recent call last):
  File "/usr/bin/oasismove", line 8, in <module>
    sys.exit(main())
  File "/root/shared/src/oasismove/run_oasis.py", line 13, in main
    from oasismove import NSfracStep
  File "/root/shared/src/oasismove/NSfracStep.py", line 68, in <module>
    vars().update(post_import_problem(**vars()))
  File "/root/shared/src/oasismove/problems/__init__.py", line 355, in post_import_problem
    assert (isinstance(mesh, Mesh))
AssertionError

```

**Comment by hkjeldsberg** [comment]
Hi @jorgensd ,

Thanks for reporting this issue. It appears that this is related to an outdated approach to fetch the Cylinder mesh from Dropbox. PR #28 should fix this issue, by including the Cylinder mesh in the repository, and also allowing the `mesh_path` command line argument if the user wants to use an arbitrary cylinder mesh. 

Best,
Henrik

**Comment by lshahid** [comment]
Hi @hkjeldsberg ,

I followed the instructions on #28 , but I am still getting the same AssertionError. I added the cylinder.xml file in the mesh/ directory and ran the command `oasismove NSfracStepMove problem=Cylinder mesh_path=mesh/cylinder.xml`. This is the error message I got:

![image](https://github.com/KVSlab/OasisMove/assets/55703996/759b9934-feee-4c1f-8813-b50aee85ce13)

I would appreciate your help with this.

Thanks,
Labib
